spring.application.name=backend

# ================== Profil actif ==================
# Active le profil "dev" pour que le DataLoader s'exécute
spring.profiles.active=dev

# ================== Configuration Base de Données ==================
spring.datasource.url=jdbc:postgresql://localhost:5432/Faso_Garages
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ================== JPA / Hibernate ==================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===== Keycloak Configuration =====
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/faso-garages

# ===== Keycloak Admin Client (pour créer des utilisateurs) =====
keycloak.server-url=http://localhost:8081
keycloak.realm=faso-garages
keycloak.client-id=faso-garages-Backend
keycloak.client-secret=8xq7UvpCaS0VfMgjyPAwt2ADTSraePfh
keycloak.admin-username=admin
keycloak.admin-password=admin
#==== j'ai remplace jwt par keycloak ====
# ================== Upload de fichiers ==================
file.upload-dir=./uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# ================== CORS ==================
cors.allowed.origins=http://localhost:4200,http://localhost:8100

# ================== OpenAPI / Swagger ==================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ================== Server ==================
server.port=8080